# This file is part of the mgWidgetsPlugin package.
# (c) 2008 MenuGourmet 
#
# Author : Thomas Rabaix <thomas.rabaix@soleoweb.com>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
mgI18nCatalogue:
  connection: <?php echo sfConfig::get('app_mgI18nPlugin_connection', 'mg_i18n_plugin') ?> 
  tableName: catalogue
  
  columns:
    cat_id: 
      type: integer
      primary: true
      autoincrement: true
    name: string(100)
    source_lang: string(100)
    target_lang: string(100)
    date_created: integer
    date_modified: integer
    author: string(255)

  relations:
    mgI18nTransUnits:
      class: mgI18nTransUnit
      local: cat_id
      foreign: cat_id
      
  options:
    collate: utf8_unicode_ci
    charset: utf8

mgI18nTransUnit:
  connection: <?php echo sfConfig::get('app_mgI18nPlugin_connection', 'mg_i18n_plugin') ?> 
  tableName: trans_unit
  
  columns:
    msg_id: 
      type: integer
      primary: true
      autoincrement: true
    cat_id: 
      type: integer
      default: 1
    id: string(255)
    source: clob
    target: clob
    comments: clob
    date_added: 
      type: integer
      default: 0
      
    date_modified:
      type: integer
      default: 0
    author: string(255)
    translated: boolean
  
  relations:
    mgI18nCatalogue:
      type: one
      local: cat_id
      foreign: cat_id
  
  options:
    collate: utf8_unicode_ci
    charset: utf8